name: LaTeX Resume to PDF
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v2
      - name: Find LaTeX resume path
        run: echo "::set-output name=LATEX_PATH::$(find *.tex -type f -printf "%p")"
        id: find-latex-path
      - name: Calculate pdf output filename
        run: echo "::set-output name=PDF_PATH::$(echo ${{ steps.find-latex-path.outputs.LATEX_PATH }} | cut -d "." -f 1 | tr -d "\n").pdf"
        id: calculate-pdf-path
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ steps.find-latex-path.outputs.LATEX_PATH }}
      - name: Release pdf
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.calculate-pdf-path.outputs.PDF_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
